[project]
name = "bandeco-alert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vitorperso_solides", email = "vitormeiragomes@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "python-dotenv>=1.2.3",
    "python-telegram-bot>=22.8",
    "requests>=2.34.2",
    "selenium>=4.47.0",
]

[project.scripts]
bandeco-alert = "bandeco_alert:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
